### ISSUE TITLE
Error authenticating jbvu_G038FEQO6JsAAAI for presence-chatroom

### ISSUE THREAD

**Issue by abrhambas01** [maitrungduc1410/realtime-chatapp-laravelecho-socketio#2]
In my `laravel-echo-server start ` part

![image](https://user-images.githubusercontent.com/12043306/81389917-31aaae00-914d-11ea-9451-c69876d66a5f.png)

**Comment by maitrungduc1410** [comment]
You're authenticating using the host `http://privatechat.example.com`, is that your host? is it running? Probably don't, that's why the error prints out "NOTFOUND" (means, can't find your host)

Make sure to set field `authHost` in `laravel-echo-server.json` to match with current context where you're running your app (Eg: in localhost, it'll be `localhost:8000`)

**Comment by abrhambas01** [comment]
bro, I want to ask something from u , and this is my `php artisan serve` tab

`laravel-echo-server.json`
```
{
	"authHost": "http://localhost:8000",
	"authEndpoint": "/broadcasting/auth",
	"clients": [],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"secureOptions": 67108864,
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"subscribers": {
		"http": true,
		"redis": true
	},
	"apiOriginAllow": {
		"allowCors": false,
		"allowOrigin": "",
		"allowMethods": "",
		"allowHeaders": ""
	}
}
```
