### ISSUE TITLE
Why does the `/rooms` route isn't in here ?

### ISSUE THREAD

**Issue by abrhambas01** [maitrungduc1410/realtime-chatapp-laravelecho-socketio#3]
Why is it not in the codebase you committed ? Please commit the updated ones please, it would mean a lot to me

**Comment by maitrungduc1410** [comment]
@abrhambas01  that's route is Vue-router, which is located at `resources/js/router.js`.

This project is made from Laravel + VueJS, so basically you'll 2 types of route:
- Backend route: routes from Laravel, which are defined in `routes/web.php`
- Frontend route: routes from VueJS, located at `resources/js/router.js`

**Comment by abrhambas01** [comment]
where can I go froin here ? 
![image](https://user-images.githubusercontent.com/12043306/81421491-26bf4000-9184-11ea-91f8-2ec7cda809e6.png)

to here

![image](https://user-images.githubusercontent.com/12043306/81421508-2de64e00-9184-11ea-825d-ffcff7d2e349.png)

Where can I go to the `#/rooms' route?

**Comment by abrhambas01** [comment]
can u push the full code, I'd be learning the whole thing ..

**Comment by maitrungduc1410** [comment]
This may take many setup steps, but you can try the following:
- Go to `resources/js/router.js`, at route name `list.room` change path to `list-room` (because currently I'm using the path `/` that's probably conflict with your route)
- Then in your first screen (as shown in the pictures above),  add an `<a>` tag, like follow:
```html
<a href="/list-room">Go to Rooms</a>
```
- Finally, go to `routes/web.php`, check if this line exists in the very bottom (it should be there if you clone my code):
```php
Route::get('/{any}', 'AppController@index')->where('any', '.*')->middleware('auth');
```

**Comment by abrhambas01** [comment]
where's the ListRoom.vue component here ?

**Comment by maitrungduc1410** [comment]
at `resources/js/pages/ListRoom.vue`

**Comment by abrhambas01** [comment]
oops sorry bro I wasn't looking at your repo I was looking at the repo that I was working on

**Comment by abrhambas01** [comment]
Bro, hey thanks a lot for the concern, I am using this tool called laragon, an alternative to someone like Xampp, it has also redis installed so probably I don't have to setup it, Can u help me on this one sir ? 

 https://github.com/leokhoa/laragon, maybe I don't have 2 install docker with it.

**Comment by abrhambas01** [comment]
Bro, should I install the Local Hypervisor along w/ it too ?

**Comment by maitrungduc1410** [comment]
> Bro, hey thanks a lot for the concern, I am using this tool called laragon, an alternative to something like Xampp, it has also redis installed so probably I don't have to setup it, Can u help me on this one sir ?
> 
> https://github.com/leokhoa/laragon, maybe I don't have 2 install docker with it.

Basically it should be same,

All you need is setup the `.env` file to match your environment: database, redis (check with `laragon`  to see)

And yes, you don't have  to install docker.  I don't have experience with Laragon so I may not able to help you

**Comment by maitrungduc1410** [comment]
> Bro, should I install the Local Hypervisor along w/ it too ? Cause I have to refresh the other window all the time.

I don't think need it for my project, not too complicated like that  :-D. If you can use docker, all you need is only docker, this is the simplest way to run my project without install anything else extra (only docker)

**Comment by abrhambas01** [comment]
the messages only reflect once I refresh the page on the other side @maitrungduc1410

**Comment by maitrungduc1410** [comment]
@abrhambas01 This is because the broadcasting part is not correctly configured:
- is the Laravel Echo Server is up, running and connectable? open your browser, check `Console` tab, is there any error related to `socket.io`, check tab `Network->WS`, can you see a socket.io websocket connection?
- is Redis up and running? open terminal/command line and run `redis-cli` is there any error ?
